[FEAT] Common Component 및 검색, 정보 입력 컴포넌트 내용 추가/수정
fire-tribes/client pull request #47
Opened 2023-09-18 14:50 UTC by Whale2200d

2023-09-18 15:04 UTC, ahn0min approved these changes

2023-09-18 15:04 UTC, ahn0min commented on components/SearchResults/index.tsx
> +        );
여기도 마찬가지 어떤 값을 return 하는지 제가 코드를 다 봐야지만 알 수 있네요 😥
`prev라는 Array를 순회하면서 선택된것 중에서 stockCode끼리 비교를 해서 동일하지 않은 것들만 담은 새 배열을 return 한다.`

아래와 같이 변경하면 더 쉽게 return 값을 파악할 수 있을 것 같습니다.
```suggestion
const stockCodeNotMatches = prev.filter(
          (selected: SelectedStocksAtomProps) =>
            selected.stockCode !== stock.stockCode,
        );
        
return stockCodeNotMatches
```

2023-09-18 15:04 UTC, ahn0min reviewed
build 결과 확인부탁드립니다

2023-09-18 15:05 UTC, ahn0min requested changes
빌드결과 확인부탁드립니다!

2023-09-18 16:54 UTC, ahn0min approved these changes

2023-09-19 00:59 UTC, Whale2200d commented on components/SearchResults/index.tsx
> +      ) {
```typescript
const isNewSelectedStocks = prev.some(selected: SelectedStocksAtomProps) => selected.stockCode === stock.stockCode)
if (isNewSelectedStocks) {
// 생략
}
```

2023-09-19 01:02 UTC, Whale2200d commented on components/SearchResults/index.tsx
> +        );
```typescript
      if (isNewSelectedStocks) {
        const notMatchedStocks = prev.filter(
          (selected: SelectedStocksAtomProps) =>
            selected.stockCode !== stock.stockCode,
        );

        return notMatchedStocks;
      } else {
        const newAddedSelectedStocks = [...prev, stock];

        return newAddedSelectedStocks;
      }
```
로 변경해봤습니다.

2023-09-19 05:45 UTC, merged